# Generated by Django 3.0.7 on 2020-07-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200706_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts, Crafts and Sewing'), ('Cars', 'Automotive parts'), ('Gene', 'General'), ('Toys', 'Toys')], default='Arts', max_length=4),
        ),
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
    ]
