# Generated by Django 3.0.7 on 2020-07-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200707_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
    ]
