# Generated by Django 3.0.7 on 2020-07-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200707_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auction',
            new_name='Auctions',
        ),
    ]
