# Generated by Django 3.0.7 on 2020-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
